name: Update README

on:
  schedule:
    - cron: '0 9 * * *' # Run every day at 09:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: |
          ./updateReadme.sh
          git config --global user.email "ben@benallen.dev"
          git config --global user.name "Ben Allen"
          git add README.md
          git commit -m "Update README"
          git push https://${{ secrets.GH_PAT}}@github.com/$GITHUB_REPOSITORY.git HEAD:main


